### ISSUE TITLE
bug: lib/utils.sh: line 27: HOME: unbound variable

### ISSUE THREAD

**Issue by n-rodriguez** [asdf-vm/asdf#1896]
### Describe the Bug

Hi there! I got this error when running `asdf plugin update --all` or `asdf plugin update nodejs` :

```sh
/Users/nicolas/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 27: HOME: unbound variable
/Users/nicolas/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 27: HOME: unbound variable
```

From https://github.com/asdf-vm/asdf-nodejs/issues/411#issuecomment-2638326045 :

> It seems the `asdf_data_dir()` function in `.asdf/plugins/nodejs/lib/utils.sh` file isn't reading the environment variables correctly. (eg. `ASDF_DATA_DIR`, `ASDF_DIR`, and `HOME`)
>
> Maybe the latest version of asdf-vm is not passing the environment variables?

Thank you!

### Steps to Reproduce

1. install asdf
2. install asdf-nodejs plugin
3. run `asdf plugin update --all` or `asdf plugin update nodejs`

### Expected Behaviour

It should update plugins without errors

### Actual Behaviour

It shows an error :

```sh
/Users/nicolas/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 27: HOME: unbound variable
```

### Environment

```shell
OS:
Darwin MacBook-Pro-de-Nicolas.local 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6020 arm64 arm Darwin

SHELL:
GNU bash, version 5.2.37(1)-release (aarch64-apple-darwin24.0.0)
Copyright (C) 2022 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>

Ceci est un logiciel libre ; vous être libre de le modifier et de le redistribuer.
AUCUNE GARANTIE n'est fournie, dans les limites permises par la loi.

BASH VERSION:
5.2.37(1)-release

ASDF VERSION:
0.16.1

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/Users/nicolas/.asdf
ASDF_CONFIG_FILE=/Users/nicolas/.asdfrc

ASDF INSTALLED PLUGINS:
...
nodejs     https://github.com/asdf-vm/asdf-nodejs.git             93bd217ba74f05080eebb7d8e1c146a385b01d7f
...
```

### asdf plugins affected (if relevant)

asdf-nodejs

**Comment by mainendra** [comment]
Is there any temporary fix for this?

**Comment by n-rodriguez** [comment]
> Is there any temporary fix for this?

Unfortunately no

**Comment by mikelkew** [comment]
@n-rodriguez this appears to be fixed in the [latest v0.16.3 release](https://github.com/asdf-vm/asdf/releases/tag/v0.16.3).

**Comment by gjoseph** [comment]
> [@n-rodriguez](https://github.com/n-rodriguez) this appears to be fixed in the [latest v0.16.3 release](https://github.com/asdf-vm/asdf/releases/tag/v0.16.3).

Didn't fix it for me :(

**Comment by Stratus3D** [comment]
Interesting @mikelkew ! I didn't expect the changes in 0.16.3 to fix this. Is anyone else here seeing this fixed with 0.16.3?

**Comment by mikelkew** [comment]
> I didn't expect the changes in 0.16.3 to fix this.

@Stratus3D Ahh, apologies. It looks like I still had some workarounds in place in my local environment that led me to believe this was resolved. Upon retesting, I now see that it's still an issue 😔

**Comment by n-rodriguez** [comment]
> Is anyone else here seeing this fixed with 0.16.3?

It's not fixed :

```sh
anicolas@MacBook-Pro-de-Nicolas:~$ asdf version
0.16.3
nicolas@MacBook-Pro-de-Nicolas:~$ asdf plugin update --all
updated bats to ref refs/heads/main
updated bombardier to ref refs/heads/master
updated crystal to ref refs/heads/master
updated earthly to ref refs/heads/main
updated golang to ref refs/heads/master
updated k3d to ref refs/heads/main
updated kompose to ref refs/heads/master
updated kubectl to ref refs/heads/master
updated mkcert to ref refs/heads/master
/Users/nicolas/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 27: HOME: unbound variable
/Users/nicolas/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 27: HOME: unbound variable
updated nodejs to ref refs/heads/master
updated overmind to ref refs/heads/master
updated packer to ref refs/heads/master
updated python to ref refs/heads/master
updated ruby to ref refs/heads/master
updated rust to ref refs/heads/master
updated shellcheck to ref refs/heads/master
updated shfmt to ref refs/heads/master
updated skaffold to ref refs/heads/main
updated squarectl to ref refs/heads/master
updated stacker to ref refs/heads/master
updated terraform to ref refs/heads/master
updated tokei to ref refs/heads/main
updated upx to ref refs/heads/main
updated xcaddy to ref refs/heads/master
updated yarn to ref refs/heads/main
updated yq to ref refs/heads/master
```

**Comment by daneroo** [comment]
This also means that the workflow on the asdf home page does not work for MacOS.

https://asdf-vm.com/guide/getting-started.html

```
> asdf list all nodejs
Plugin nodejs's list-all callback script failed with output:
Trying to update node-build... ok
```

**Comment by sigaocaue** [comment]
The issue persists for me. I’m using the following versions:
`asdf version 0.16.4`
`nodejs https://github.com/asdf-vm/asdf-nodejs.git`
`nodejs 93bd217ba74f05080eebb7d8e1c146a385b01d7f`

When running the command asdf plugin update nodejs, I’m getting the following output:
```
/Users/caueprado/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 27: HOME: unbound variable
/Users/caueprado/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 27: HOME: unbound variable
updated nodejs to ref refs/heads/master
```
The `$HOME` variable is set: `/Users/caueprado`
The `$ASDF_DATA_DIR` variable is set: `/Users/caueprado/.asdf`

Does anyone know **how to fix this issue**?

**Comment by Stratus3D** [comment]
This should be fixed by https://github.com/asdf-vm/asdf/pull/1982
