### ISSUE TITLE
"No version is set" when version is set and returned by `asdf current`.

### ISSUE THREAD

**Issue by adamu** [asdf-vm/asdf#488]
### Steps to reproduce

I'm setting up a dockerfile based on alpine linux for an elixir build environment.
Here is an example session:

```
$ echo $PATH
/root/.asdf/bin:/root/.asdf/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.0
<clones asdf...>
$ asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
<installs elixir plugin...>
$ asdf install elixir 1.8
==> Copying release into place
$ asdf global elixir 1.8
$ asdf current
elixir         1.8      (set by /root/.tool-versions)
$ which elixir
/root/.asdf/shims/elixir
$ asdf which elixir
asdf: No version set for command elixir
you might want to add one of the following in your .tool-versions file:
$ elixir
asdf: No version set for command elixir
you might want to add one of the following in your .tool-versions file:
```

### Expected behavior
`asdf which elixir` should return version 1.8 and `elixir` should execute the binary.

### Actual behavior

```
asdf: No version set for command elixir
you might want to add one of the following in your .tool-versions file:
```

### Environment

**OS**: Alpine Linux in a docker container

**asdf version**: 0.7.0

Here is the WIP Dockerfile:

```Dockerfile
FROM alpine:3.9

ENV ASDF_VERSION "v0.7.0"
ENV ERLANG_VERSION "21.3"
ENV ELIXIR_VERSION "1.8"

RUN apk add --update --no-cache bash git curl perl alpine-sdk autoconf ncurses ncurses-dev && \
      git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch $ASDF_VERSION && \
      echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc

SHELL ["/bin/bash", "-ic"]

RUN asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git && \
      asdf install elixir $ELIXIR_VERSION && \
      asdf global elixir $ELIXIR_VERSION


ENTRYPOINT bash 
```

**Comment by hez** [comment]
I am getting this in a lot of languages after updating to the latest ver.

**Comment by danhper** [comment]
Could you give it a try on master and let us know how that goes please?

**Comment by adamu** [comment]
Same results on master:

```
bash-4.4# pwd
/root/.asdf
bash-4.4# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
bash-4.4# asdf current
elixir         1.8      (set by /root/.tool-versions)
bash-4.4# asdf which elixir
asdf: No version set for command elixir
you might want to add one of the following in your .tool-versions file:
```

**Comment by adamu** [comment]
I downgraded to 0.6.3, and it's working there:

```
bash-4.4# git log -1 | cat -n
     1  commit 1886e00cf18f5e9d3c5ac1bd18426d04121d4472
     2  Author: John Doe <jdoe@example.com>
     3  Date:   Sat Jan 19 09:14:56 2019 -0500
     4
     5      Update version to 0.6.3
bash-4.4# asdf which elixir
/root/.asdf/installs/elixir/1.8/bin/elixir
```

**Comment by danhper** [comment]
Thanks for trying out. I will take a closer look.

**Comment by danhper** [comment]
@adamu Thanks a lot for the report and the Dockerfile.
This should now be fixed. Could you give it another try and let me know how it goes please?
Thank you.

@hez Could you please check if your issue is fixed on the master branch please? If it is not, could you please open another issue with a little more information about your environment. Thank you.

**Comment by adamu** [comment]
Works on master for me.

```
bash-4.4# echo $ASDF_VERSION
master
bash-4.4# asdf which elixir
/root/.asdf/installs/elixir/1.8/bin/elixir
```

**Comment by danhper** [comment]
Yes, we'll release a new version very soon!

**Comment by jpinnix** [comment]
Just a note that I also had this issue, tested against master and now it works.

**Comment by hez** [comment]
👍looks to be resolved in the latest ver

**Comment by danhper** [comment]
Thanks for your help! 0.7.1 should work how you expect!

**Comment by bowmanmike** [comment]
Hey, I'm still having this same issue with asdf version `0.7.1` and ruby. I've got my `.ruby-version` file in the directory, and my `~/.asdfrc` has `legacy_version_file = yes`. I'm on a Mac running High Sierra, and the required Ruby version is installed.


![image](https://user-images.githubusercontent.com/15827207/56140763-88a17c00-5f69-11e9-8bad-4e012464f549.png)

**Comment by Stratus3D** [comment]
@bowmanmike it looks like you've specified Ruby version `2.3.4` but don't have that version installed (see the list in your screenshot that printed with you ran `ruby --version`). Installing that version of Ruby should fix the issue. Feel free to create another issue to improve the error message here. The version is set, but that version is not installed. The message could definitely be improved.

**Comment by bowmanmike** [comment]
@Stratus3D I do have `2.3.4` installed, as shown here:
![image](https://user-images.githubusercontent.com/15827207/56143084-e33cd700-5f6d-11e9-8af6-7ace03da604c.png)

**Comment by Stratus3D** [comment]
Maybe try `asdf reshim`? If that version is installed and you've set that version in your directory it should work. If this issue manifests in multiple directories or across multiple plugins (e.g. elixir, python, etc...) please open a new issue.

**Comment by bowmanmike** [comment]
That seemed to work! Thanks!

**Comment by eksperimental** [comment]
still having this issue with v0.7.1 even after `asdf reshim`

I'm getting 

```
$ iex
asdf: No version set for command iex
you might want to add one of the following in your .tool-versions file:

elixir 1.4.4
elixir 1.7.4
elixir 1.8.0
elixir 1.8.1
```

and my .tool-versions is

```
erlang 21.0.6
elixir path:/home/eksperimental/elixir
```

**Comment by danhper** [comment]
@eksperimental Could you open another issue please? I suppose there has been a regression for how we handle `path: ` versions.

**Comment by 7stud** [comment]
I installed a new version of elixir, then I updated asdf, and now I get the error:

```
~$ iex
asdf: No version set for command iex
you might want to add one of the following in your .tool-versions file:
elixir 1.6.6
```
More info:

```
~$ asdf list elixir
  1.6.6
  1.8.2
~$ asdf current
elixir         1.8.2    (set by /Users/7stud/.tool-versions)
erlang         20.3     (set by /Users/7stud/.tool-versions)

~$ iex
asdf: No version set for command iex
you might want to add one of the following in your .tool-versions file:

elixir 1.6.6
~$ 
```

**Comment by eksperimental** [comment]
@7stud this has been fixed on master in #524
Does it work?

**Comment by joemsak** [comment]
v0.7.2 on a fresh mojave install here, same problem with ruby, reshim does nothing

the following is a sample of some of the trouble I had in commandline, as I had rebooted in an effort to fix it

```
> ruby -v
fasdf: No version set for command ruby
you might want to add one of the following in your .tool-versions file:

ruby 2.6.3
> asdf local ruby 2.3.3

> [useless use of] cat .tool-versions 
ruby 2.3.3
nodejs 9.11.2
python 3.7.3

> ruby -v
asdf: No version set for command ruby
you might want to add one of the following in your .tool-versions file:

ruby 2.6.3

> bundle
asdf: No version set for command bundle
you might want to add one of the following in your .tool-versions file:

ruby 2.6.3
> gem install bundler
asdf: No version set for command gem
you might want to add one of the following in your .tool-versions file:

ruby 2.6.3
> ruby -v
asdf: No version set for command ruby
you might want to add one of the following in your .tool-versions file:

ruby 2.6.3
> asdf install ruby 2.3.3
ruby 2.3.3 is already installed
>asdf local ruby 2.3.3  
> asdf reshim ruby
> ruby -v
asdf: No version set for command ruby
you might want to add one of the following in your .tool-versions file:

ruby 2.6.3
> asdf list ruby
  2.3.3
  2.6.3
> asdf --version
v0.7.2
> ```

**Comment by joemsak** [comment]
Heads up, it might be related to downgrading from the Catalina beta - https://twitter.com/infinitebrkfst/status/1141395765731790848 - my only problem on the beta was how piss-poor Finder was performing: constant beachball for normal tasks such as alt-tabbing from another app to Finder, or selecting a file to highlight it, or closing the finder window

**Comment by kvokka** [comment]
I'm using macOS 10.14.5 Mochave (and I did not even tried to install 10.15), but i'm facing the same issue.

I even tried to remove all previous ruby installations with no luck.

```
$ cat ~/.tool-versions
ruby 2.6.3
$ asdf list ruby
  --definitions
  2.6.3
$ ruby -v
asdf: No version set for command ruby
you might want to add one of the following in your .tool-versions file:

ruby 2.6.3
```

**Comment by kvokka** [comment]
@adamu @danhper Can you, please, re-open the issue? Or it is better to create the new one?

**Comment by danhper** [comment]
I don't think the issue you are having is the same one as the original one so could you please open a new issue with a description of your problem. Thanks!

**Comment by kvokka** [comment]
Occasionally I got this issue again, with trying to make fresh installation of ruby 2.1.10. (so it was impossible to run bundler with 2.1.10)

It was surprisingly resolved with installing ruby 2.1.9, and after it bundler works in both versions. Maybe it help someone

**Comment by kaka-ruto** [comment]
`gem update --system` solved for me, incase you messed up your system gems like me

**Comment by mconyango** [comment]
Run these commands:
`asdf global elixir <version>`
`asdf global erlang <version>`

To check the version of elixir or erlang run this command:
`asdf list elixir` or `asdf list erlang`
